name 'cowdugChef-azure'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cowdugChef-azure'
long_description 'Installs/Configures cowdugChef-azure'
version '0.1.0'
